name: agendamentos_app
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.1.2
dependencies:
  flutter:
    sdk: flutter


  cloud_firestore: ^4.8.3
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  syncfusion_flutter_calendar: ^22.1.38
  firebase_messaging: ^14.6.7
  intl: ^0.18.0
  firebase_storage: ^11.2.6
  flutter_local_notifications: ^15.1.0+1
  brasil_fields: ^1.14.0
  syncfusion_flutter_pdfviewer: ^22.2.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/imagens/teste2.png
    - assets/imagens/password.png
  